# Generated by Django 5.2.12 on 2026-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_contact_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('brands', models.CharField(blank=True, max_length=255, null=True)),
                ('countries', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(default='openfoodfacts', max_length=50)),
            ],
        ),
    ]
