# Generated by Django 5.2.12 on 2026-04-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='barcode',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='brands',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='countries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
